server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: 2667960113
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org:
        springframework:
          web: INFO
      spring:
        security: INFO
